version: '3.8'

services:
  node-server:
    build: ./node-server
    image: studio-server:v1.0.0
    container_name: node-server
    ports:
      - "${PORT}:3000"
    environment:
      - NODE_ENV=production
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - PASSWORD_HASHING_SEED=${PASSWORD_HASHING_SEED}
      - TOKEN_EXPIRATION=${TOKEN_EXPIRATION}
      - REFRESH_TOKEN_EXPIRATION=${REFRESH_TOKEN_EXPIRATION}
    depends_on:
      - mysql-db
    networks:
      - app-network
    # Volumes section removed as per previous recommendations

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3310:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  mysql-backup:
    build:
      context: ./mysql-backup
      dockerfile: Dockerfile
    container_name: mysql-backup
    environment:
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./db_backups:/backups
    depends_on:
      - mysql-db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
